FROM openjdk:17-jdk-slim
RUN mkdir /app
# Esegue la build dell'applicazione utilizzando Maven
COPY ./pom.xml /app
RUN cd /app && mvn clean package
# Copia il file JAR generato nella cartella /app
COPY ./target/customer-spring.jar /app
WORKDIR /app
CMD ["java", "-jar", "customer-spring.jar"]