FROM maven:3.6.3-jdk-8 as build

COPY ./src /usr/src/customer-spring/src
COPY ./pom.xml /usr/src/customer-spring

RUN mvn -f /usr/src/customer-spring/pom.xml clean package

FROM openjdk:8-jdk-alpine

COPY --from=build /usr/src/customer-spring/target/customer-spring-0.0.1-SNAPSHOT.jar /app/app.jar

EXPOSE 8080

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]
