version: '3'
services:
  customer:
    image: lorenzoparisidocker/customer
    container_name: customer-container
    ports:
      - 8080:8080
    environment:
      - SPRING.DATA.MONGODB.URI=mongodb://mongo:27017/test
    networks:
      - provaNetwork
    command: dockerun
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    networks:
      - provaNetwork
    restart: always

networks:
  provaNetwork:
