FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal AS base
WORKDIR /app
EXPOSE 80
FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /src
COPY ["Borrowings.WebApi.csproj", "./"]
RUN dotnet restore "./Borrowings.WebApi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Borrowings.WebApi.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "Borrowings.WebApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Borrowings.WebApi.dll"]