FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
EXPOSE 80
EXPOSE 443
ENV ASPNETCORE_URLS http://*:5010
ENV ASPNETCORE_ENVIRONMENT=Development
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "Borrowings.WebApi.dll" ]
